---
swagger: '2.0'
info:
  title: Jira data source
  version: '1.0'
  description: Jira data source V2
paths:    # swagger forces me to add at least one path
  /noop:
    get:
      description: no-op
      responses:
        200:
          description: ok
definitions:
  DataSource:
    type: object
    properties:
      Slug:
        type: string
        example: jira
      Name:
        type: string
        example: Jira
  MetaData:
    type: object
    properties:
      BackendName:
        type: string
        example: insights-datasource-jira
      BackendVersion:
        type: string
        example: v0.1.0
      Project:
        type: string
        example: Hyperledger Sawtooth
      Tags:
        type: array
        items:
          type: string
          example: my-tag
  Identity:
    type: object
    properties:
      Id:
        type: string
        example: 1234567890abcdef
        description: PK - up to 50 chars
      Name:
        type: string
        example: Lukasz Gryglicki
      Username:
        type: string
        example: lgryglicki
      DataSourceId:
        type: string
        example: jira
        description: data source type slug (FK)
  IssueActivity:
    type: object
    properties:
      Id:
        type: string
        example: 1234567890abcdef
        description: PK - up to 50 chars
      IssueKey:
        type: string
        example: 1234567890abcdef
        description: FK - up to 50 chars, points to Issue.Id
      IssueId:
        type: string
        example: 1234567890abcdef
        description: points to Issue.IssueId 
      ParentKey:
        type: string
        x-nullable: true
        example: 1234567890abcdef
        description: FK - up to 50 chars, points to Issue.Id (comments have a parent issue for instance)
      ParentIssueId:
        type: string
        x-nullable: true
        example: 1234567890abcdef
        description: points to Issue.IssueId (comments have a parent issue for instance)
      CreatedAt:
        type: string
        format: date-time
        example: '2019-09-02 03:00:33.000000'
      CreatedTz:
        type: string
        example: Europe/Warsaw (FIXME - confirm)
      ActivityType:
        type: string
        example: FIXME provide full list
        description: allows reconstructing relations
      Body:
        type: string
        description: issue/comment body
        example: My comment body
        x-nullable: true
      Identity:
        type: object
        description: activity creator (ProjectDataSourceIdentity)
        $ref: "#/definitions/Identity"
  Issue:
    type: object
    properties:
      Id:
        type: string
        example: 1234567890abcdef
        description: PK - up to 50 chars
      IssueId:
        type: string
        example: 1234567890abcdef
        description: Jira internal issue ID
      CreatedAt:
        type: string
        format: date-time
      CreatedTz:
        type: string
        example: Europe/Warsaw (FIXME - confirm)
      UpdatedAt:
        type: string
        format: date-time
        example: '2019-09-02 03:00:33.000000'
      UpdatedTz:
        type: string
        example: Europe/Warsaw (FIXME - confirm)
      URL:
        type: string
        example: https://msg-url
      Title:
        type: string
        example: My issue title
      Watchers:
        type: integer
        example: 2
      IsClosed:
        type: boolean
        example: false
      DataSourceId:
        type: string
        example: jira
        description: data source type slug (FK)
      Activities:
        type: array
        items:
          $ref: "#/definitions/IssueActivity"
      Labels:
        type: array
        items:
          type: string
  Event:
    type: object
    description: single event in Jira is an issue, it contains neted activities for that issue
    properties:
      Issue:
        type: object
        $ref: "#/definitions/Issue"
  Data:
    type: object
    description: this is the final output of insights-datasource-jira, data source will output packs up to some fixed size, like 500 events pack at once
    properties:
      DataSource:
        type: object
        $ref: "#/definitions/DataSource"
      MetaData:
        type: object
        $ref: "#/definitions/MetaData"
      Endpoint:
        type: string
        description: Jira endpoint for which data is being sent
        example: https://jira.onap.org
      Events:
        type: array
        items:
          $ref: "#/definitions/Event"
